### ISSUE TITLE
Error building on Vercel

### ISSUE THREAD

**Issue by phocks** [Rich-Harris/sveltekit-on-the-edge#4]
Hi there,

I'm getting this error on a completely new build on Vercel template.

```
[15:02:16.583] Cloning github.com/phocks/sveltekit-edge-functions (Branch: main, Commit: 87e6c84)
[15:02:17.492] Cloning completed: 908.212ms
[15:02:17.860] Looking up build cache...
[15:02:17.989] Build Cache not found
[15:02:18.282] Running "vercel build"
[15:02:18.891] Vercel CLI 25.1.0 build (beta) — https://vercel.com/feedback
[15:02:19.214] Installing dependencies...
[15:02:19.867] Lockfile is up-to-date, resolution step is skipped
[15:02:19.893] Progress: resolved 1, reused 0, downloaded 0, added 0
[15:02:19.931] Packages: +98
[15:02:19.931] ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
[15:02:20.323] Packages are hard linked from the content-addressable store to the virtual store.
[15:02:20.323]   Content-addressable store is at: /vercel/.pnpm-store/v3
[15:02:20.324]   Virtual store is at:             node_modules/.pnpm
[15:02:20.898] Progress: resolved 98, reused 0, downloaded 44, added 43
[15:02:21.900] Progress: resolved 98, reused 0, downloaded 94, added 94
[15:02:22.916] Progress: resolved 98, reused 0, downloaded 98, added 98, done
[15:02:22.951] .../node_modules/svelte-preprocess postinstall$ echo "[svelte-preprocess] Don't forget to install the preprocessors packages that will be used: node-sass/sass, stylus, less, postcss & postcss-load-config, coffeescript, pug, etc..."
[15:02:22.966] .../node_modules/svelte-preprocess postinstall: [svelte-preprocess] Don't forget to install the preprocessors packages that will be used: node-sass/sass, stylus, less, postcss & postcss-load-config, coffeescript, pug, etc...
[15:02:22.967] .../node_modules/svelte-preprocess postinstall: Done
[15:02:22.973] .../esbuild@0.14.37/node_modules/esbuild postinstall$ node install.js
[15:02:23.060] .../esbuild@0.14.37/node_modules/esbuild postinstall: Done
[15:02:23.119] 
[15:02:23.119] devDependencies:
[15:02:23.119] + @sveltejs/adapter-auto 1.0.0-next.35
[15:02:23.120] + @sveltejs/adapter-vercel 1.0.0-next.48
[15:02:23.120] + @sveltejs/kit 1.0.0-next.317
[15:02:23.120] + prettier 2.6.2
[15:02:23.120] + prettier-plugin-svelte 2.7.0
[15:02:23.120] + svelte 3.47.0
[15:02:23.121] + svelte-check 2.7.0
[15:02:23.121] + typescript 4.6.3
[15:02:23.121] 
[15:02:23.121] 
[15:02:23.122] > what-is-my-ip@0.0.1 prepare /vercel/path0
[15:02:23.122] > svelte-kit sync
[15:02:23.122] 
[15:02:23.543] Running "pnpm run build"
[15:02:24.139] 
[15:02:24.139] > what-is-my-ip@0.0.1 build /vercel/path0
[15:02:24.139] > svelte-kit build
[15:02:24.140] 
[15:02:24.496] [36mvite v2.9.5 [32mbuilding for production...[36m[39m
[15:02:24.624] transforming...
[15:02:25.813] [32m✓[39m 23 modules transformed.
[15:02:25.891] rendering chunks...
[15:02:25.913] [90m[37m[2m.svelte-kit/output/client/_app/[22m[90m[39m[32massets/twitter-card-24d4d63c.jpg        [39m [2m104.71 KiB[22m
[15:02:25.915] [90m[37m[2m.svelte-kit/output/client/_app/[22m[90m[39m[32mmanifest.json                           [39m [2m1.27 KiB[22m
[15:02:25.918] [90m[37m[2m.svelte-kit/output/client/_app/[22m[90m[39m[36mlayout.svelte-1492f025.js               [39m [2m0.53 KiB / gzip: 0.35 KiB[22m
[15:02:25.919] [90m[37m[2m.svelte-kit/output/client/_app/[22m[90m[39m[36merror.svelte-fcba5de1.js                [39m [2m1.56 KiB / gzip: 0.75 KiB[22m
[15:02:25.919] [90m[37m[2m.svelte-kit/output/client/_app/[22m[90m[39m[36mchunks/index-c531e97c.js                [39m [2m7.25 KiB / gzip: 2.95 KiB[22m
[15:02:25.919] [90m[37m[2m.svelte-kit/output/client/_app/[22m[90m[39m[36mstart-d33b84c8.js                       [39m [2m23.03 KiB / gzip: 8.65 KiB[22m
[15:02:25.920] [90m[37m[2m.svelte-kit/output/client/_app/[22m[90m[39m[35massets/pages/index.svelte-d9835f54.css  [39m [2m4.85 KiB / gzip: 1.30 KiB[22m
[15:02:25.920] [90m[37m[2m.svelte-kit/output/client/_app/[22m[90m[39m[36mpages/index.svelte-757b6e6d.js          [39m [2m19.05 KiB / gzip: 6.15 KiB[22m
[15:02:25.931] [36mvite v2.9.5 [32mbuilding SSR bundle for production...[36m[39m
[15:02:26.056] transforming...
[15:02:26.507] [32m✓[39m 21 modules transformed.
[15:02:26.535] Generated an empty chunk: "hooks"
[15:02:26.544] rendering chunks...
[15:02:26.563] [90m[37m[2m.svelte-kit/output/server/[22m[90m[39m[32mmanifest.json                       [39m [2m1.36 KiB[22m
[15:02:26.564] [90m[37m[2m.svelte-kit/output/server/[22m[90m[39m[36mindex.js                            [39m [2m75.32 KiB[22m
[15:02:26.564] [90m[37m[2m.svelte-kit/output/server/[22m[90m[39m[36mentries/endpoints/index.js          [39m [2m0.18 KiB[22m
[15:02:26.564] [90m[37m[2m.svelte-kit/output/server/[22m[90m[39m[36mentries/fallbacks/layout.svelte.js  [39m [2m0.24 KiB[22m
[15:02:26.564] [90m[37m[2m.svelte-kit/output/server/[22m[90m[39m[36mentries/fallbacks/error.svelte.js   [39m [2m0.72 KiB[22m
[15:02:26.565] [90m[37m[2m.svelte-kit/output/server/[22m[90m[39m[36mentries/pages/index.svelte.js       [39m [2m17.57 KiB[22m
[15:02:26.565] [90m[37m[2m.svelte-kit/output/server/[22m[90m[39m[36mchunks/index-937793ff.js            [39m [2m2.62 KiB[22m
[15:02:26.565] [90m[37m[2m.svelte-kit/output/server/[22m[90m[39m[36mchunks/hooks-1c45ba0b.js            [39m [2m0.00 KiB[22m
[15:02:26.586] 
[15:02:26.586] Run npm run preview to preview your production build locally.
[15:02:26.589] 
[15:02:26.590] > Using @sveltejs/adapter-vercel
[15:02:26.590] > edge and split options can only be used with ENABLE_VC_BUILD
[15:02:26.591]     at adapt (file:///vercel/path0/node_modules/.pnpm/@sveltejs+adapter-vercel@1.0.0-next.48/node_modules/@sveltejs/adapter-vercel/index.js:93:12)
[15:02:26.591]     at adapt (file:///vercel/path0/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.317_svelte@3.47.0/node_modules/@sveltejs/kit/dist/chunks/index4.js:181:8)
[15:02:26.591]     at file:///vercel/path0/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.317_svelte@3.47.0/node_modules/@sveltejs/kit/dist/cli.js:937:11
[15:02:26.601]  ELIFECYCLE  Command failed with exit code 1.
[15:02:26.627] Error! Command "pnpm run build" exited with 1
[15:02:26.699] Error: Command "vercel build" exited with 1
```

**Comment by animemandir** [comment]
Im getting the same error but on a unrelated and different svelte web app

**Comment by garyhe0780** [comment]
@phocks 
I think the error msg pretty much told why building was wrong
you need add `ENABLE_VC_BUILD` to your environments and set it to be `1`

**Comment by phocks** [comment]
Whoops I forgot to read the README too which specifies that you need to set that to make it work.
